name: sqlite3_flutter_libs
description: Flutter plugin to include native sqlite3 libraries with your app
version: 0.4.0+1
homepage: https://github.com/simolus3/sqlite3.dart/tree/master/sqlite3_flutter_libs
issue_tracker: https://github.com/simolus3/sqlite3.dart/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.1"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: eu.simonbinder.sqlite3_flutter_libs
        pluginClass: Sqlite3FlutterLibsPlugin
      ios:
        pluginClass: Sqlite3FlutterLibsPlugin